import Link from "next/link";
import {driveImageUrl} from "@/lib/googleDrive";
import s from "./AboutEditorial.module.css";
export default function AboutEditorial(){return <div className={s.story}>
 <header className={s.opening}><p className={s.kicker}>About / Ivonne Aldaz</p><h1>The World Is<br/><em>My Studio.</em></h1><div className={s.introLine}><span>Strategy · Technology · Art · Teaching</span><a href="mailto:hello@ivonnealdaz.com">Let’s talk ↗</a></div></header>
 <section className={s.portraitStory} aria-labelledby="about-story-title"><figure className={s.portrait}><img src={driveImageUrl('1UJ7HG3gZU2zD5Y_kdHwCXLGjm1llx_Xc')} alt="Ivonne Aldaz"/><figcaption>Ivonne Aldaz / Strategist, artist, builder, educator</figcaption></figure><div className={s.storyText}><span className={s.kicker}>A personal introduction</span><h2 id="about-story-title">Two languages.<br/>Two worlds.<br/><em>A constant curiosity.</em></h2><p>I grew up on the border. Two languages, two worlds. A constant pull toward the other side.</p><p>For over a decade, I’ve been building brands and shaping how companies think, look, and communicate. I keep coming back to what makes something resonate—and what makes people feel something before they can explain why.</p><p>That curiosity moves between strategy, technology, teaching, and making things with my hands.</p></div></section>
 <nav className={s.chapterNav} aria-label="Explore my practice"><a href="#about-strategy">01 / Strategy</a><a href="#about-technology">02 / Technology</a><a href="#about-art">03 / Art</a><a href="#about-teaching">04 / Teaching</a></nav>
 <section className={s.practice} aria-label="Four parts of my practice"><article id="about-strategy" className={s.strategy}><span className={s.kicker}>01 / Strategy</span><h2>Building brands<br/>with a point of view.</h2><p>Whitespace is my strategy and creative studio. My work spans brand positioning, consumer insights, creative direction, and the systems that turn a strategy into something people experience.</p><a href="https://www.bywhitespace.com/" target="_blank" rel="noreferrer">Explore Whitespace ↗</a><Link href="/#case-studies">Selected case studies →</Link></article><article id="about-technology" className={s.technology}><span className={s.kicker}>02 / Technology</span><div className={s.systemDiagram} aria-hidden="true"><span>an idea</span><i>↓</i><span>a working system</span><i>↓</i><span>something useful</span></div><h2>Thinking by building.</h2><p>Digital tools, AI, automation, and independent experiments. A way to test an idea is to make it work.</p><a href="https://lab.ivonnealdaz.com" target="_blank" rel="noreferrer">Explore the Lab ↗</a></article><article id="about-art" className={s.art}><div className={s.artImages}><img src="/editorial/art.webp" alt="Paintings exhibited in a gallery" loading="lazy"/><img src="/editorial/dolomites.webp" alt="A landscape from my travels in the Dolomites" loading="lazy"/></div><span className={s.kicker}>03 / Art + place</span><h2>Something I can’t undo<br/>with a keystroke.</h2><p>In marketing, everything moves quickly. I needed to make something that could outlive the next campaign, so I paint and work in ceramics.</p><p>Art residencies in France and Italy cracked something open in me. Place, light, and the experience of being somewhere new keep finding their way into the work.</p><Link href="/art">View my art practice →</Link><a href="https://www.goodworldliving.com" target="_blank" rel="noreferrer">Good World Living ↗</a></article><article id="about-teaching" className={s.teaching}><span className={s.kicker}>04 / Teaching + community</span><h2>Making room<br/>for other ideas.</h2><p>Teaching marketing and entrepreneurship, mentoring founders, and participating in the arts community are part of the same practice.</p><p>Sharing what I know—and staying open to what I haven’t learned yet.</p><a href="#background">Teaching, experience + community ↓</a><div className={s.marginNote}><span>A note to keep close</span><blockquote>Life is about saying yes to the things that will make a better story.</blockquote></div></article></section>
 <section className={s.closing}><p>Sometimes it’s a painting. Sometimes it’s a brand.<br/>Sometimes it’s a weird little thing I build on the internet.</p><span>Different expressions of the same curiosity.</span></section>
 <div id="background" className={s.backgroundHeading}><span className={s.kicker}>The background</span><h2>Experience + credentials.</h2><p>The roles, collaborations, and learning behind the work.</p></div>
 </div>}
